In [7]:
#Data ( Student Marks Analyzer student data )
import numpy as np
marks = np.loadtxt('student_marks_100_records.csv',delimiter=',',skiprows=1,usecols=(2,3,4,5,6))
print(marks)
roll_no = np.loadtxt('student_marks_100_records.csv',delimiter=',',skiprows=1,usecols=(0),dtype=int)

#Total marks of each student

total_marks = np.sum(marks,axis=1)
total = np.column_stack((roll_no, total_marks))
print(total)

#Average marks of each student

avarage = np.mean(marks,axis=1)
mean = np.column_stack((roll_no, avarage))
print(mean)

#Highest scorer
import numpy as np

# Load structured data from CSV
dtype_schema = [
    ('Roll_No', 'i4'),
    ('Student_Name', 'U50'),
    ('Math', 'i4'),
    ('Physics', 'i4'),
    ('Chemistry', 'i4'),
    ('English', 'i4'),
    ('Computer', 'i4')
]

data = np.genfromtxt('student_marks_100_records.csv', delimiter=',', skip_header=1, dtype=dtype_schema, encoding='utf-8')

# Calculate total marks for each student
subject_matrix = np.column_stack([data['Math'], data['Physics'], data['Chemistry'], data['English'], data['Computer']])
total_marks = np.sum(subject_matrix, axis=1)

# Get index of the max total score
top_idx = np.argmax(total_marks)
lowest_idx = np.argmin(total_marks)

# Print top scorer details
top_student = data[top_idx]
print(f"Top Scorer: {top_student['Student_Name']} (Roll No: {top_student['Roll_No']})")
print(f"Lowest Scorer: {data[lowest_idx]['Student_Name']} (Roll No: {data[lowest_idx]['Roll_No']})")

#Avarage

marks = np.loadtxt('student_marks_100_records.csv', delimiter=',', skiprows=1, usecols=(2, 3, 4, 5, 6))
subject_averages = np.mean(marks, axis=0)
subjects = ['Math', 'Physics', 'Chemistry', 'English', 'Computer']
for subj, avg in zip(subjects, subject_averages):
    print(f"{subj} Class Average: {avg:.2f}%")
    overall_avg = np.mean(marks)
print(f"\nOverall Class Average: {overall_avg:.2f}%")

#subject wise avarage

marks = np.loadtxt('student_marks_100_records.csv', delimiter=',', skiprows=1, usecols=(2, 3, 4, 5, 6))
subjects = ['Math', 'Physics', 'Chemistry', 'English', 'Computer']
subject_averages = np.mean(marks, axis=0)

for subject, avg in zip(subjects, subject_averages):
    print(f"{subject}: {avg:.2f}%")

#Highest mark in each subject

dtype_schema = [
    ('Roll_No', 'i4'),
    ('Student_Name', 'U50'),
    ('Math', 'i4'),
    ('Physics', 'i4'),
    ('Chemistry', 'i4'),
    ('English', 'i4'),
    ('Computer', 'i4')
]

data = np.genfromtxt('student_marks_100_records.csv', delimiter=',', skip_header=1, dtype=dtype_schema, encoding='utf-8')
subjects = ['Math', 'Physics', 'Chemistry', 'English', 'Computer']
for subj in subjects:
    max_score = np.max(data[subj])
    matching_indices = np.where(data[subj] == max_score)[0]

    print(f"\n{subj} (Highest Score: {max_score}):")
    for idx in matching_indices:
        student = data[idx]
        print(f"  - {student['Student_Name']} (Roll No: {student['Roll_No']})")

#Lowest mark in each subject

for subj in subjects:
    min_score = np.min(data[subj])
    matching_indices = np.where(data[subj] == min_score)[0]

    print(f"\n{subj} (Lowest Score: {min_score}):")
    for idx in matching_indices:
        student = data[idx]
        print(f"  - {student['Student_Name']} (Roll No: {student['Roll_No']})")

#Students scoring above 80 average

data = np.genfromtxt('student_marks_100_records.csv', delimiter=',', skip_header=1, dtype=dtype_schema, encoding='utf-8')
subject_matrix = np.column_stack([data['Math'], data['Physics'], data['Chemistry'], data['English'], data['Computer']])
averages = np.mean(subject_matrix, axis=1)
# Boolean masking to find students with average > 80
mask = averages > 80
high_achievers = data[mask]
high_averages = averages[mask]
for student, avg in zip(high_achievers, high_averages):
    print(f"Roll {student['Roll_No']}: {student['Student_Name']} -> Average: {avg:.2f}%")

    #Students scoring below 40 in any subject


    marks = np.loadtxt('student_marks_100_records.csv', delimiter=',', skiprows=1, usecols=(2, 3, 4, 5, 6))
    failing_mask = np.any(marks < 40, axis=1)
    num_students = np.sum(failing_mask)

print(f"Number of students scoring below 40 in any subject: {num_students}")
print(f"Lowest score in the entire dataset: {np.min(marks)}")


[[85. 52. 46. 92. 62.]
 [60. 59. 53. 92. 51.]
 [88. 92. 79. 50. 82.]
 [72. 47. 46. 50. 58.]
 [59. 77. 83. 46. 80.]
 [57. 90. 86. 89. 79.]
 [71. 59. 73. 82. 62.]
 [96. 45. 93. 96. 55.]
 [89. 72. 66. 62. 54.]
 [58. 93. 66. 51. 50.]
 [69. 51. 67. 67. 83.]
 [61. 96. 47. 91. 74.]
 [79. 52. 69. 50. 80.]
 [63. 98. 85. 84. 68.]
 [81. 57. 90. 49. 47.]
 [87. 59. 94. 63. 50.]
 [59. 51. 69. 62. 74.]
 [85. 98. 68. 55. 68.]
 [67. 58. 87. 62. 89.]
 [88. 86. 49. 83. 85.]
 [55. 79. 91. 60. 55.]
 [74. 69. 62. 85. 89.]
 [80. 59. 88. 65. 98.]
 [94. 94. 48. 59. 97.]
 [47. 96. 65. 70. 62.]
 [49. 58. 81. 90. 65.]
 [58. 86. 76. 70. 86.]
 [74. 54. 61. 53. 60.]
 [92. 80. 79. 61. 92.]
 [82. 72. 82. 70. 68.]
 [59. 53. 77. 76. 50.]
 [93. 48. 52. 54. 85.]
 [55. 95. 88. 72. 83.]
 [49. 69. 69. 83. 74.]
 [78. 61. 80. 45. 88.]
 [91. 52. 88. 79. 93.]
 [62. 94. 86. 66. 52.]
 [63. 72. 55. 74. 45.]
 [91. 91. 61. 77. 93.]
 [56. 77. 51. 85. 64.]
 [98. 85. 77. 83. 57.]
 [54. 68. 93. 55. 79.]
 [94. 78. 45. 83. 65.]
 [76. 46. 5